
- name: ensure MySQL is installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ freebsd_mysql_packages }}"
  tags:
  - install

- name: ensure MySQL enabled in rc.conf
  command: sysrc -f /etc/rc.conf mysql_enable=YES
  register: sysrc_changed
  changed_when:  "'YES -> YES' not in sysrc_changed.stdout"
  tags:
  - startup

- name: ensure folders exist for innodb
  file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0750
  with_items:
  - "{{ freebsd_mysql_innodb_data_dir }}"
  - "{{ freebsd_mysql_innodb_log_dir }}"
  tags:
  - install
  - dataset

- name: ensure backup recovery folder exists
  file:
    path: "{{ freebsd_mysql_backup_location }}"
    state: directory
    owner: mysql
    group: mysql
  tags:
  - import

- name: ensure my.cnf is properly setup
  ini_file:
    dest: /usr/local/etc/{{ freebsd_mysql_vendor}}/my.cnf
    section: "{{ item.section | default('mysqld') }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ freebsd_mysql_config }}"
  notify: restart mysql
  tags:
  - configure

- name: ensure pip is installed for downloading MySQLdb
  command: python -m ensurepip
  args:
    creates: /usr/local/bin/pip
  when: freebsd_mysql_install_mysqldb
  tags:
  - install

- name: ensure pip installs MySQL-python
  command: pip install MySQL-python
  when: freebsd_mysql_install_mysqldb
  register: mysql_python_installed
  changed_when: "'Requirement already satisfied' not in mysql_python_installed.stdout"
  tags:
  - install

- name: ensure MySQL will be started
  service:
    name: "{{ freebsd_mysql_service }}"
    state: started
  tags:
  - startup
