---
# tasks file for bvansomeren.freebsd-mysql

- include: install.yml
  tags: install

- include: secure.yml
  tags: secure

- include: databases.yml
  tags: databases

- include: users.yml
  tags: users

    #Totally borked
  #- include: replication.yml
  #tags: replication
  #when: freebsd_mysql_replication_role is defined
  #static: no
