---
# tasks file for bvansomeren.freebsd-mysql

- include: install.yml
  tags: install

- include: secure.yml
  tags: secure

- include: databases.yml
  tags: databases

- include: users.yml
  tags: users
