
- name: check if /root/.mysql_secret exists
  stat:
    path: /root/.mysql_secret
  register: mysql_secret

- debug:
    var: mysql_secret

- name: divine the generated root password from MySQL instal
  shell: "tail -n1 /root/.mysql_secret"
  register: mysql_secret_password
  when: mysql_secret.stat.exists

- name: ensure MySQL root user password is set
  command: /usr/local/bin/mysqladmin -u root -p{{ mysql_secret_password.stdout }} password "{{ freebsd_mysql_rootpw }}"
  when: freebsd_mysql_changerootpw or mysql_secret.stat.exists
  register: mysql_rootpw_set

- name: ensure /root/.mysql_secret is removed when we are done
  file:
    path: /root/.mysql_secret
    state: absent
  when: mysql_rootpw_set.changed and mysql_secret.stat.exists

- name: ensure users can login as root using ~/.my.cnf
  blockinfile:
    dest: "{{ item }}/.my.cnf"
    create: yes
    marker: "# {mark} .my.cnf for this server"
    content: |
      [client]
      user=root
      password={{ freebsd_mysql_rootpw }}
  with_items: "{{ _freebsd_mysql_adminusers }}"
